# Generated by Django 4.0.1 on 2022-02-11 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_product_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
