# Generated by Django 4.0.1 on 2022-02-11 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0009_alter_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorite_products", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
