# Generated by Django 4.0.1 on 2022-02-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_product_favorites"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_usd",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
