# Generated by Django 4.0.1 on 2022-02-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_product_cost_usd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cost_usd",
            field=models.FloatField(default=0),
        ),
    ]
