# Generated by Django 4.0.1 on 2022-02-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_product_cost_usd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="external_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
